micronaut:
  application:
    name: designPattern
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/learningcenter
    driverClassName: org.postgresql.Driver
    username: postgres
    password: aryan
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

